[package]
name = "haeng"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.3", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
url = "2.3.1"
once_cell = "1.17.0"
